name: CICD Pipeline

on:
  push:
    branches:
      - develop

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        run: |
          docker buildx build --cache-to=type=local,dest=/tmp/.buildx-cache \
                              --cache-from=type=local,src=/tmp/.buildx-cache \
                              -t ${{ secrets.DOCKERHUB_USERNAME }}/englebee-test:latest \
                              --push .

      - name: Deploy to EC2
        uses: appleboy/ssh-action@v0.1.2
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            # 이전에 실행 중이던 컨테이너 중지 및 삭제
            docker stop englebee || true
            docker rm englebee || true

            # 최신 Docker 이미지 가져오기
            docker pull ${{ secrets.DOCKERHUB_USERNAME }}/englebee-test:latest

            # Spring Boot 애플리케이션 Docker 컨테이너 실행
            docker run -d \
              --name englebee \
              -e SPRING_DATASOURCE_URL=${{ secrets.SPRING_DATASOURCE_URL }} \
              -e SPRING_DATASOURCE_USERNAME=${{ secrets.SPRING_DATASOURCE_USERNAME }} \
              -e SPRING_DATASOURCE_PASSWORD=${{ secrets.SPRING_DATASOURCE_PASSWORD }} \
              -p 8080:8080 \
              ${{ secrets.DOCKERHUB_USERNAME }}/englebee-test:latest
