name: CICD Pipeline

on:
  push:
    branches:
      - develop

jobs:
  # Docker 이미지를 빌드하고 Docker Hub에 푸시하는 작업
  build-docker-image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@v3

      # 1. Docker 이미지를 먼저 빌드
      - name: Build Docker image
        run: docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/englebee-test:latest .

      # 2. DockerHub 로그인 (빌드 후 로그인)
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # 3. Docker 이미지를 Docker Hub에 푸시
      - name: Push Docker image to Docker Hub
        run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/englebee-test:latest

  # Docker 이미지를 EC2에서 실행하는 작업
  run-docker-image-on-ec2:
    needs: build-docker-image
    runs-on: ubuntu-latest

    steps:
      # SSH 클라이언트 설치
      - name: Install SSH client
        run: sudo apt-get install -y openssh-client

      # SSH 키 설정
      - name: Add SSH key
        run: echo "${{ secrets.EC2_SSH_KEY }}" > key.pem && chmod 600 key.pem

      # EC2에서 Docker 명령어 실행
      - name: SSH and Run Docker Commands on EC2
        run: |
          ssh -o StrictHostKeyChecking=no -i key.pem ubuntu@${{ secrets.AWS_EC2_IP }} << 'EOF'
            # Docker 명령어를 실행할 사용자에 Docker 권한 추가
            sudo usermod -aG docker $USER

            # Docker Hub에서 최신 이미지를 가져오기
            sudo docker pull ${{ secrets.DOCKERHUB_USERNAME }}/englebee-test:latest

            # 실행 중인 컨테이너 중지 및 삭제
            sudo docker stop englebee || true
            sudo docker rm englebee || true

            # 새 컨테이너 실행
            sudo docker run --name englebee --rm -d -p 8080:8080 ${{ secrets.DOCKERHUB_USERNAME }}/englebee-test:latest

            # 불필요한 Docker 시스템 캐시 정리
            sudo docker system prune -f
          EOF
